export const CAT_COLORS = {
  'Sembako': '#3B82F6',
  'Sayur & Buah': '#22C55E',
  'Protein & Daging': '#EF4444',
  'Pupuk & Pertanian': '#EAB308',
  'Pakan Ternak': '#F97316',
  'Makanan Olahan': '#A855F7',
  'Minuman': '#06B6D4',
  'ATK & Perlengkapan': '#6B7280'
};

export const VENDORS = [
  { id:'VND-001', nama:'UD Sumber Rejeki', kategori:'Sembako', jenis:'Distributor', desa:'Sardonoharjo', kecamatan:'Ngaglik', alamat:'Jl. Kaliurang KM 12 No. 8', lat:-7.6783, lng:110.4012, kontak:'0812-2700-1101', produk:'Beras, gula, minyak goreng, tepung', kapasitas:'18 ton/bln', minOrder:'5 karung', metodeBayar:['Tunai','Transfer','Tempo'], rating:4.6, jam:'07.00-17.00', catatan:'Bisa tempo 14 hari untuk koperasi terdaftar', stok:'tersedia' },
  { id:'VND-002', nama:'Tani Makmur Poktan', kategori:'Sayur & Buah', jenis:'Petani/Poktan', desa:'Donoharjo', kecamatan:'Ngaglik', alamat:'Dusun Ngepringan RT 03', lat:-7.6691, lng:110.3847, kontak:'0813-2811-2205', produk:'Sawi, cabai, tomat, kol, bayam', kapasitas:'6 ton/bln', minOrder:'20 kg', metodeBayar:['Tunai','Transfer'], rating:4.4, jam:'06.00-14.00', catatan:'Panen harian, stok tergantung musim', stok:'tersedia' },
  { id:'VND-003', nama:'CV Berkah Protein', kategori:'Protein & Daging', jenis:'Distributor', desa:'Sinduharjo', kecamatan:'Ngaglik', alamat:'Jl. Damai No. 21', lat:-7.6912, lng:110.3958, kontak:'0856-4300-7788', produk:'Ayam potong, telur, ikan beku', kapasitas:'9 ton/bln', minOrder:'10 kg', metodeBayar:['Transfer','Tempo'], rating:4.7, jam:'05.00-15.00', catatan:'Punya cold storage, pengiriman pagi', stok:'tersedia' },
  { id:'VND-004', nama:'Toko Tani Subur', kategori:'Pupuk & Pertanian', jenis:'Grosir', desa:'Sukoharjo', kecamatan:'Ngaglik', alamat:'Jl. Palagan Tentara Pelajar KM 9', lat:-7.7024, lng:110.3889, kontak:'0878-3900-4412', produk:'Pupuk NPK, urea, pestisida, bibit', kapasitas:'25 ton/bln', minOrder:'1 sak', metodeBayar:['Tunai','Transfer'], rating:4.3, jam:'07.30-16.30', catatan:'Stok pupuk bersubsidi terbatas', stok:'tersedia' },
  { id:'VND-005', nama:'Mandiri Pakan Ternak', kategori:'Pakan Ternak', jenis:'Produsen', desa:'Sardonoharjo', kecamatan:'Ngaglik', alamat:'Dusun Candi RT 01', lat:-7.6745, lng:110.3955, kontak:'0851-0122-3390', produk:'Pakan ayam, pakan ikan, konsentrat sapi', kapasitas:'14 ton/bln', minOrder:'2 sak', metodeBayar:['Tunai','Tempo'], rating:4.5, jam:'08.00-17.00', catatan:'Produksi sendiri, harga relatif stabil', stok:'tersedia' },
  { id:'VND-006', nama:'UMKM Snack Bu Yati', kategori:'Makanan Olahan', jenis:'UMKM', desa:'Sendangadi', kecamatan:'Mlati', alamat:'Jl. Magelang KM 7 Gg. Melati', lat:-7.7298, lng:110.3621, kontak:'0813-9000-5567', produk:'Keripik, rempeyek, kerupuk, kue kering', kapasitas:'1.2 ton/bln', minOrder:'5 kg', metodeBayar:['Tunai','QRIS'], rating:4.8, jam:'08.00-20.00', catatan:'Produk titip jual, bisa private label', stok:'tersedia' },
  { id:'VND-007', nama:'Grosir Sembako Amanah', kategori:'Sembako', jenis:'Grosir', desa:'Tlogoadi', kecamatan:'Mlati', alamat:'Jl. Kebonagung No. 15', lat:-7.7411, lng:110.3402, kontak:'0812-1500-8821', produk:'Beras, mie instan, kopi, susu, sabun', kapasitas:'22 ton/bln', minOrder:'3 karton', metodeBayar:['Tunai','Transfer','Tempo'], rating:4.5, jam:'06.30-18.00', catatan:'Melayani retur barang rusak', stok:'tersedia' },
  { id:'VND-008', nama:'Sayur Segar Tirtoadi', kategori:'Sayur & Buah', jenis:'Petani/Poktan', desa:'Tirtoadi', kecamatan:'Mlati', alamat:'Dusun Janturan RT 05', lat:-7.7489, lng:110.3289, kontak:'0857-2900-1144', produk:'Kangkung, terong, timun, kacang panjang', kapasitas:'4.5 ton/bln', minOrder:'15 kg', metodeBayar:['Tunai'], rating:4.2, jam:'05.30-12.00', catatan:'Gabungan beberapa petani, kualitas variatif', stok:'tersedia' },
  { id:'VND-009', nama:'CV Logam Jaya ATK', kategori:'ATK & Perlengkapan', jenis:'Distributor', desa:'Sumberadi', kecamatan:'Mlati', alamat:'Jl. Cebongan No. 9', lat:-7.7356, lng:110.3478, kontak:'0878-2100-6633', produk:'ATK, nota, struk, perlengkapan toko', kapasitas:'3 ton/bln', minOrder:'10 pak', metodeBayar:['Transfer','QRIS'], rating:4.4, jam:'08.00-16.00', catatan:'Cocok untuk kebutuhan operasional koperasi', stok:'tersedia' },
  { id:'VND-010', nama:'Toko Buah Maguwo', kategori:'Sayur & Buah', jenis:'Grosir', desa:'Maguwoharjo', kecamatan:'Depok', alamat:'Jl. Ringroad Utara No. 88', lat:-7.7612, lng:110.4123, kontak:'0813-2700-9988', produk:'Pisang, jeruk, semangka, salak, apel', kapasitas:'7 ton/bln', minOrder:'10 kg', metodeBayar:['Tunai','Transfer'], rating:4.6, jam:'06.00-19.00', catatan:'Salak pondoh lokal, harga grosir', stok:'tersedia' },
  { id:'VND-011', nama:'UD Daging Berkah Maguwo', kategori:'Protein & Daging', jenis:'Distributor', desa:'Maguwoharjo', kecamatan:'Depok', alamat:'Jl. Nangka II No. 3', lat:-7.7689, lng:110.4056, kontak:'0851-3300-2211', produk:'Daging sapi, ayam, telur', kapasitas:'8 ton/bln', minOrder:'5 kg', metodeBayar:['Transfer','Tempo'], rating:4.5, jam:'05.00-14.00', catatan:'Sertifikat halal, ada nota resmi', stok:'tersedia' },
  { id:'VND-012', nama:'Beras Asli Condongcatur', kategori:'Sembako', jenis:'Produsen', desa:'Condongcatur', kecamatan:'Depok', alamat:'Jl. Gejayan No. 45', lat:-7.7589, lng:110.3934, kontak:'0812-2600-7733', produk:'Beras premium, beras medium, menir', kapasitas:'16 ton/bln', minOrder:'5 karung', metodeBayar:['Tunai','Transfer'], rating:4.7, jam:'07.00-17.00', catatan:'Penggilingan sendiri, bisa custom kemasan', stok:'tersedia' },
  { id:'VND-013', nama:'Warung Grosir Caturtunggal', kategori:'Sembako', jenis:'Grosir', desa:'Caturtunggal', kecamatan:'Depok', alamat:'Jl. Seturan Raya No. 12', lat:-7.7823, lng:110.4067, kontak:'0856-2900-3344', produk:'Gula, minyak, garam, bumbu dapur', kapasitas:'12 ton/bln', minOrder:'2 karton', metodeBayar:['Tunai','QRIS','Tempo'], rating:4.3, jam:'07.00-21.00', catatan:'Buka sampai malam, cocok restock cepat', stok:'tersedia' },
  { id:'VND-014', nama:'Kelompok Tani Sumber Pangan', kategori:'Sayur & Buah', jenis:'Petani/Poktan', desa:'Sukoharjo', kecamatan:'Ngaglik', alamat:'Dusun Gondanglegi RT 02', lat:-7.7056, lng:110.3812, kontak:'0857-3800-5599', produk:'Cabai rawit, bawang merah, jahe, kunyit', kapasitas:'3.8 ton/bln', minOrder:'10 kg', metodeBayar:['Tunai','Transfer'], rating:4.4, jam:'06.00-13.00', catatan:'Komoditas rempah, harga fluktuatif', stok:'tersedia' },
  { id:'VND-015', nama:'UMKM Tempe Pak Karto', kategori:'Makanan Olahan', jenis:'UMKM', desa:'Sinduharjo', kecamatan:'Ngaglik', alamat:'Dusun Rejodani RT 04', lat:-7.6878, lng:110.4001, kontak:'0813-2800-1212', produk:'Tempe, tahu, oncom', kapasitas:'2.5 ton/bln', minOrder:'10 papan', metodeBayar:['Tunai','QRIS'], rating:4.7, jam:'04.00-12.00', catatan:'Produksi harian segar, antar pagi', stok:'tersedia' },
  { id:'VND-016', nama:'Distributor Air Minum Tirta', kategori:'Minuman', jenis:'Distributor', desa:'Sendangadi', kecamatan:'Mlati', alamat:'Jl. Magelang KM 8 No. 30', lat:-7.7256, lng:110.3589, kontak:'0878-3300-7700', produk:'Air galon, air kemasan, teh kemasan', kapasitas:'20 ton/bln', minOrder:'5 dus', metodeBayar:['Tunai','Transfer','Tempo'], rating:4.5, jam:'07.00-18.00', catatan:'Pengantaran rutin terjadwal', stok:'tersedia' },
  { id:'VND-017', nama:'Toko Kelontong Rahayu', kategori:'Sembako', jenis:'UMKM', desa:'Sardonoharjo', kecamatan:'Ngaglik', alamat:'Dusun Sawahan RT 06', lat:-7.6712, lng:110.3878, kontak:'0851-2200-8866', produk:'Sembako eceran, rokok, jajanan', kapasitas:'2 ton/bln', minOrder:'1 karton', metodeBayar:['Tunai','QRIS'], rating:4.1, jam:'06.00-22.00', catatan:'Skala kecil, cocok untuk restock darurat', stok:'tersedia' },
  { id:'VND-018', nama:'CV Mitra Pangan Sleman', kategori:'Sembako', jenis:'Distributor', desa:'Tlogoadi', kecamatan:'Mlati', alamat:'Jl. Kebonagung KM 3', lat:-7.7445, lng:110.3356, kontak:'0812-2900-4455', produk:'Beras, gula, tepung, minyak curah', kapasitas:'24 ton/bln', minOrder:'10 karung', metodeBayar:['Transfer','Tempo'], rating:4.6, jam:'07.00-16.30', catatan:'Volume besar, harga kompetitif untuk koperasi', stok:'tersedia' },
  { id:'VND-019', nama:'Peternakan Telur Donoharjo', kategori:'Protein & Daging', jenis:'Produsen', desa:'Donoharjo', kecamatan:'Ngaglik', alamat:'Dusun Tegalrejo RT 01', lat:-7.6634, lng:110.3789, kontak:'0857-2700-9911', produk:'Telur ayam, telur bebek', kapasitas:'6 ton/bln', minOrder:'10 kg', metodeBayar:['Tunai','Transfer'], rating:4.6, jam:'06.00-15.00', catatan:'Stok telur konsisten, harga harian', stok:'tersedia' },
  { id:'VND-020', nama:'UMKM Gula Semut Merapi', kategori:'Makanan Olahan', jenis:'UMKM', desa:'Donoharjo', kecamatan:'Ngaglik', alamat:'Dusun Ngepringan RT 07', lat:-7.6678, lng:110.3812, kontak:'0813-3100-2244', produk:'Gula semut, gula merah, madu', kapasitas:'0.8 ton/bln', minOrder:'5 kg', metodeBayar:['Tunai','QRIS'], rating:4.8, jam:'08.00-16.00', catatan:'Produk organik, potensi ekspor', stok:'tersedia' },
  { id:'VND-021', nama:'Grosir Plastik & Kemasan Jaya', kategori:'ATK & Perlengkapan', jenis:'Grosir', desa:'Caturtunggal', kecamatan:'Depok', alamat:'Jl. Babarsari No. 19', lat:-7.7812, lng:110.4123, kontak:'0878-2900-3311', produk:'Plastik, kemasan, kantong, label', kapasitas:'5 ton/bln', minOrder:'5 pak', metodeBayar:['Tunai','Transfer'], rating:4.3, jam:'08.00-17.00', catatan:'Kebutuhan kemasan produk UMKM', stok:'tersedia' },
  { id:'VND-022', nama:'Tani Hidroponik Tirtoadi', kategori:'Sayur & Buah', jenis:'Produsen', desa:'Tirtoadi', kecamatan:'Mlati', alamat:'Dusun Pundong RT 03', lat:-7.7523, lng:110.3245, kontak:'0851-3400-7788', produk:'Selada, pakcoy, bayam hidroponik', kapasitas:'2.2 ton/bln', minOrder:'5 kg', metodeBayar:['Transfer','QRIS'], rating:4.7, jam:'07.00-15.00', catatan:'Kualitas premium, kontinuitas terjaga', stok:'tersedia' },
  { id:'VND-023', nama:'UD Sembako Sumberadi', kategori:'Sembako', jenis:'Grosir', desa:'Sumberadi', kecamatan:'Mlati', alamat:'Jl. Cebongan No. 22', lat:-7.7389, lng:110.3512, kontak:'0812-2400-6677', produk:'Beras, mie, gula, kopi, teh', kapasitas:'15 ton/bln', minOrder:'3 karton', metodeBayar:['Tunai','Transfer','Tempo'], rating:4.4, jam:'06.30-18.00', catatan:'Langganan beberapa koperasi desa', stok:'tersedia' },
  { id:'VND-024', nama:'Pakan & Obat Ternak Sehat', kategori:'Pakan Ternak', jenis:'Distributor', desa:'Sukoharjo', kecamatan:'Ngaglik', alamat:'Jl. Palagan KM 10 No. 5', lat:-7.7089, lng:110.3923, kontak:'0857-3900-1100', produk:'Pakan ternak, vitamin, obat hewan', kapasitas:'10 ton/bln', minOrder:'2 sak', metodeBayar:['Tunai','Tempo'], rating:4.5, jam:'08.00-17.00', catatan:'Konsultasi peternakan gratis', stok:'tersedia' },
  { id:'VND-025', nama:'Toko Buah & Sayur Sendangadi', kategori:'Sayur & Buah', jenis:'Grosir', desa:'Sendangadi', kecamatan:'Mlati', alamat:'Jl. Magelang KM 6 No. 14', lat:-7.7234, lng:110.3645, kontak:'0813-2200-5544', produk:'Buah campur, sayur mayur harian', kapasitas:'5.5 ton/bln', minOrder:'10 kg', metodeBayar:['Tunai','QRIS'], rating:4.2, jam:'05.00-17.00', catatan:'Pasokan harian dari pasar induk', stok:'tersedia' },
  { id:'VND-026', nama:'CV Beras Tani Mlati', kategori:'Sembako', jenis:'Produsen', desa:'Tlogoadi', kecamatan:'Mlati', alamat:'Dusun Jetis RT 02', lat:-7.7467, lng:110.3423, kontak:'0851-2900-8822', produk:'Beras IR64, beras Mentik, dedak', kapasitas:'17 ton/bln', minOrder:'5 karung', metodeBayar:['Tunai','Transfer','Tempo'], rating:4.6, jam:'07.00-16.00', catatan:'Hasil panen lokal, harga stabil', stok:'tersedia' },
  { id:'VND-027', nama:'UMKM Kopi Lereng Merapi', kategori:'Minuman', jenis:'UMKM', desa:'Sardonoharjo', kecamatan:'Ngaglik', alamat:'Dusun Candi RT 05', lat:-7.6723, lng:110.3989, kontak:'0878-2700-6655', produk:'Kopi bubuk, kopi biji, kopi sachet', kapasitas:'0.6 ton/bln', minOrder:'3 kg', metodeBayar:['Tunai','QRIS'], rating:4.9, jam:'08.00-18.00', catatan:'Specialty coffee, branding kuat', stok:'tersedia' },
  { id:'VND-028', nama:'Distributor Sayur Pasar Induk', kategori:'Sayur & Buah', jenis:'Distributor', desa:'Maguwoharjo', kecamatan:'Depok', alamat:'Jl. Ringroad Utara No. 120', lat:-7.7634, lng:110.4089, kontak:'0812-3100-9900', produk:'Sayur grosir, bumbu, rempah', kapasitas:'13 ton/bln', minOrder:'20 kg', metodeBayar:['Tunai','Transfer','Tempo'], rating:4.3, jam:'03.00-11.00', catatan:'Buka dini hari, harga termurah', stok:'tersedia' },
  { id:'VND-029', nama:'Toko Higienis & Sanitasi', kategori:'ATK & Perlengkapan', jenis:'Grosir', desa:'Condongcatur', kecamatan:'Depok', alamat:'Jl. Kaliurang KM 6 No. 33', lat:-7.7523, lng:110.3978, kontak:'0857-2400-3322', produk:'Sabun, deterjen, tisu, pembersih', kapasitas:'6 ton/bln', minOrder:'5 dus', metodeBayar:['Transfer','QRIS'], rating:4.4, jam:'08.00-17.00', catatan:'Kebutuhan non-pangan koperasi', stok:'tersedia' },
  { id:'VND-030', nama:'Madu & Herbal Nusantara', kategori:'Makanan Olahan', jenis:'UMKM', desa:'Sinduharjo', kecamatan:'Ngaglik', alamat:'Dusun Ngabean RT 08', lat:-7.6934, lng:110.3912, kontak:'0851-3300-4477', produk:'Madu, jamu instan, herbal', kapasitas:'0.9 ton/bln', minOrder:'3 kg', metodeBayar:['Tunai','QRIS'], rating:4.7, jam:'08.00-16.00', catatan:'Produk herbal lokal, margin tinggi', stok:'tersedia' }
];

export const KOPDES = [
  { id:'KOP-01', nama:'Kopdes Merah Putih Sardonoharjo', desa:'Sardonoharjo', kecamatan:'Ngaglik', alamat:'Balai Desa Sardonoharjo', lat:-7.6756, lng:110.3923, anggota:612, gudang:true, kebutuhan:'Sembako, pupuk, pakan ternak', kontak:'0812-2700-0001', catatan:'Punya gudang sedang, jadi hub klaster utara' },
  { id:'KOP-02', nama:'Kopdes Merah Putih Donoharjo', desa:'Donoharjo', kecamatan:'Ngaglik', alamat:'Jl. Ngepringan No. 2', lat:-7.6667, lng:110.3823, anggota:438, gudang:false, kebutuhan:'Sayur, sembako, sarana tani', kontak:'0813-2800-0002', catatan:'Volume kecil, sering pengadaan gabungan' },
  { id:'KOP-03', nama:'Kopdes Merah Putih Sinduharjo', desa:'Sinduharjo', kecamatan:'Ngaglik', alamat:'Balai Desa Sinduharjo', lat:-7.6901, lng:110.3945, anggota:575, gudang:true, kebutuhan:'Sembako, protein, pakan', kontak:'0856-4300-0003', catatan:'Dekat distributor protein, biaya antar rendah' },
  { id:'KOP-04', nama:'Kopdes Merah Putih Sukoharjo', desa:'Sukoharjo', kecamatan:'Ngaglik', alamat:'Jl. Palagan KM 9', lat:-7.7033, lng:110.3878, anggota:521, gudang:false, kebutuhan:'Pupuk, pakan ternak, sembako', kontak:'0878-3900-0004', catatan:'Basis pertanian, kebutuhan sarana tani tinggi' },
  { id:'KOP-05', nama:'Kopdes Merah Putih Sendangadi', desa:'Sendangadi', kecamatan:'Mlati', alamat:'Balai Desa Sendangadi', lat:-7.7278, lng:110.3612, anggota:689, gudang:true, kebutuhan:'Sembako, air minum, ATK', kontak:'0813-9000-0005', catatan:'Anggota terbanyak, jadi hub klaster barat' },
  { id:'KOP-06', nama:'Kopdes Merah Putih Tlogoadi', desa:'Tlogoadi', kecamatan:'Mlati', alamat:'Jl. Kebonagung No. 4', lat:-7.7423, lng:110.3389, anggota:496, gudang:false, kebutuhan:'Sembako, sayur, kemasan', kontak:'0812-1500-0006', catatan:'Dekat banyak grosir sembako' },
  { id:'KOP-07', nama:'Kopdes Merah Putih Maguwoharjo', desa:'Maguwoharjo', kecamatan:'Depok', alamat:'Jl. Ringroad Utara No. 90', lat:-7.7623, lng:110.4101, anggota:734, gudang:true, kebutuhan:'Sembako, buah, protein', kontak:'0813-2700-0007', catatan:'Akses jalan besar, cocok titik bongkar muat besar' },
  { id:'KOP-08', nama:'Kopdes Merah Putih Condongcatur', desa:'Condongcatur', kecamatan:'Depok', alamat:'Jl. Gejayan No. 50', lat:-7.7578, lng:110.3945, anggota:803, gudang:true, kebutuhan:'Sembako, sanitasi, ATK', kontak:'0812-2600-0008', catatan:'Wilayah padat, perputaran cepat' }
];

// Demo scenario: Klaster Ngaglik (3 kopdes, 2 vendor)
export const DEMO = {
  kopdesIds: ['KOP-01', 'KOP-02', 'KOP-04'],
  vendorIds: ['VND-001', 'VND-004'],
  kebutuhan: [
    { kopdesId:'KOP-01', kategori:'Sembako', item:'Beras', jumlah:500, satuan:'kg' },
    { kopdesId:'KOP-01', kategori:'Pupuk & Pertanian', item:'Pupuk NPK', jumlah:100, satuan:'kg' },
    { kopdesId:'KOP-02', kategori:'Sembako', item:'Beras', jumlah:300, satuan:'kg' },
    { kopdesId:'KOP-02', kategori:'Pupuk & Pertanian', item:'Pupuk NPK', jumlah:50, satuan:'kg' },
    { kopdesId:'KOP-04', kategori:'Sembako', item:'Beras', jumlah:400, satuan:'kg' },
    { kopdesId:'KOP-04', kategori:'Pupuk & Pertanian', item:'Pupuk NPK', jumlah:150, satuan:'kg' }
  ]
};

export function buildVendorContext() {
  return VENDORS.map((v, i) =>
    `${i+1}. ${v.nama} (${v.id}) — ${v.kategori}, ${v.desa}, ${v.kecamatan}\n   Produk: ${v.produk}\n   Kapasitas: ${v.kapasitas} | Min Order: ${v.minOrder} | Bayar: ${v.metodeBayar.join('/')}\n   Rating: ${v.rating}/5 | Jam: ${v.jam} | Stok: ${v.stok}\n   Info: ${v.catatan}`
  ).join('\n\n');
}
